<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ruo</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(\{)</string>
	<key>foldingStopMarker</key>
	<string>(\})</string>
	<key>name</key>
	<string>Ruota</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_double</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_single</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_regex</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number_int</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number_hex</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support_function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support_variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support_type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_params</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_usage</string>
		</dict>
		<dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expr</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.vim</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#.*$</string>
					<key>name</key>
					<string>comment.line.quotes.ruota</string>
				</dict>
			</array>
		</dict>
		<key>expr</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\*|\+|\-|\/|\%|\&|\||\=|\:|\>|\<|\!|\.|\~|\@)</string>
					<key>name</key>
					<string>keyword.operator.ruota</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w+(?=\.)</string>
					<key>name</key>
					<string>storage.function.ruota</string>
				</dict>
			</array>
		</dict>
		<key>function_definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w+(?=\(.*\)\s*\=\>)</string>
					<key>name</key>
					<string>entity.name.function.ruota</string>
				</dict>
			</array>
		</dict>
		<key>function_usage</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\w+\s*(?=\())</string>
					<key>name</key>
					<string>entity.name.function.ruota</string>
				</dict>
			</array>
		</dict>
		<key>function_params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>-\w+=</string>
					<key>name</key>
					<string>support.type.ruota</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(do|then|in|from|return|static|var|dynamic|else|break|new|switch|local|virtual)\b</string>
					<key>name</key>
					<string>keyword.control.ruota</string>
				</dict>
			</array>
		</dict>
		<key>number_int</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b-?\d+\.?\d*\b</string>
					<key>name</key>
					<string>constant.numeric.integer</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_double</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\"(\\\\|\\"|[^\n"])*\"</string>
					<key>name</key>
					<string>string.quoted.double.ruota</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_single</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>'(\\\\|\\'|[^\n'])*'</string>
					<key>name</key>
					<string>string.quoted.single.ruota</string>
				</dict>
			</array>
		</dict>
		<key>string_regex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\"(\\\\|\\/|[^\n/])*\"</string>
					<key>name</key>
					<string>string.regexp.ruota</string>
				</dict>
			</array>
		</dict>
		<key>support_function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(idem|_OUTER_CALL_|thread|detach|self)\b</string>
					<key>name</key>
					<string>support.function.ruota</string>
				</dict>
			</array>
		</dict>
		<key>support_variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(keys|get|load|len|arr|chr|str|alloc|type|num|push|pop|mov|post|end|null|struct|true|false)\b</string>
					<key>name</key>
					<string>keyword.other.ruota</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\w+\s*(?=\:\:)</string>
					<key>name</key>
					<string>variable.other.ruota</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ruota</string>
	<key>uuid</key>
	<string>0555180C-1AF8-4D94-9937-4434C2AE07E5</string>
</dict>
</plist>
